### ISSUE TITLE
[S] Populate School Years pages with content

### ISSUE THREAD

**Issue by tkeburia** [redbadger/esma-website#55]
AC:
 * inline references should link to footnotes at the end of the page
- [ ] populate copy into MDX files for each page
- [ ] set up config required for ResearchNavigation (i.e. pills) to work

**Comment by ramsayalbazzaz** [comment]
- "Issues Chronology" should be highlighted in the Nav whenever anyone is on these pages.
- In the breadcrumbs "Overview" should say "Life stage overview"
-The icon on the 'Next up' button is wrong. It has the Early Years icon instead of school years
-Spacing between body copy seems quite large and more than in Zeplin
-Footnote links don't think yet - Will this be done later?
-On mobile is it possible to highlight which section the user is on in the contents drop down?

@tkeburia @rjkerrison @cameronramsay @carinapope13 @sjltaylor
